### PR TITLE
Refactor of tengbe.py code

### PR DESCRIPTION
**Pull request by telegraphic**
My [previous pull request](https://github.com/casper-astro/casperfpga/pull/21) added a `setup()` and `configure_core()` function for manual configuration of the 10 GbE core.

I have since learned that the location of registers changed to make it mem-map-compliant (@jack-h thinks in August 2019). This PR should work with both (although I think someone should test it on their designs and confirm I haven't broken anything).

The first thing to note is that I've added text files for both the new 'unified' memory map and the 'legacy' verson. These list register names, offsets, and sizes:

```
ID              OFFSET      SIZE        READ/WRITE
...
MAC_ADDR        0xc         0x8         rw
IP_ADDR         0x14        0x4         rw
GW_ADDR         0x18        0x4         rw
...
```

This is more compact and readable (IMO) then having them defined at the top of `tengbe.py` -- particularly as most of these aren't used at all in the code. Then I've added a function to read these files, to compile a dictionary of mappings:

```python
memmap = {'MAC_ADDR': {'offset': 0xc, 'size': 0x8, 'rwflag': 'rw'},
          'IP_ADDR': {'offset' 0x14, 'size': 0x4, 'rwflag': 'rw'}}
```
Upon instantiation, the tengbe code will check which mapping to use. 

Next I added `_memmap_read()` and `_memmap_write()` functions, which are used whenever a register needs to be read or written. These functions work with 1, 2, 4 and 8 Byte registers (which requires a bit of book-keeping as only 32-bit words can actually be read or written). 

This simplifies a lot of code, making it more readable. For example, the new `configure_core()` function is:

```python
    def configure_core(self):
        """
        Setup the interface by writing to the fabric directly, bypassing tap.
        :param self:
        :return:
        """
        gateway = 1 if self.gateway is None else self.gateway.ip_int

        self._memmap_write('MAC_ADDR', self.mac.mac_int)
        self._memmap_write('IP_ADDR',  self.ip_address.ip_int)
        self._memmap_write('NETMASK',  self.subnet_mask.ip_int)
        self._memmap_write('GW_ADDR',  gateway)
        self._memmap_write('PORT',     self.port)

        self.fabric_enable()
        self.fabric_soft_reset_toggle()
```

Which I think is a lot clearer than `struct.pack('>LLBHHLB', huge, list, of, vars, and, zeros, here)`.

And this code
```python
        if self.memmap_compliant:
            data = self.parent.read(self.name, 16384)
            data = list(struct.unpack('>16384B', data))
            returnval = {
                'ip_prefix': '%i.%i.%i.' % (data[0x14], data[0x15], data[0x16]),
                'ip': IpAddress('%i.%i.%i.%i' % (data[0x14], data[0x15], 
                                                 data[0x16], data[0x17])),
                'subnet_mask': IpAddress('%i.%i.%i.%i' % (
                                  data[0x1c], data[0x1d], data[0x1e], data[0x1f])),
                'mac': Mac('%i:%i:%i:%i:%i:%i' % (data[0x0e], data[0x0f],
                                                  data[0x10], data[0x11],
                                                  data[0x12], data[0x13])),
                'gateway_ip': IpAddress('%i.%i.%i.%i' % (data[0x18], data[0x19],
                                                         data[0x1a], data[0x1b])),
                'fabric_port': ((data[0x32] << 8) + (data[0x33])),
                'fabric_en': bool(data[0x2f] & 1),
                'multicast': {'base_ip': IpAddress('%i.%i.%i.%i' % (
                    data[0x20], data[0x21], data[0x22], data[0x23])),
                              'ip_mask': IpAddress('%i.%i.%i.%i' % (
                                  data[0x24], data[0x25], data[0x26], data[0x27])),
                              'rx_ips': []}
            }
        else:
            data = self.parent.read(self.name, 16384)
            data = list(struct.unpack('>16384B', data))
            returnval = {
                'ip_prefix': '%i.%i.%i.' % (data[0x10], data[0x11], data[0x12]),
                'ip': IpAddress('%i.%i.%i.%i' % (data[0x10], data[0x11], 
                                                 data[0x12], data[0x13])),
                'subnet_mask': IpAddress('%i.%i.%i.%i' % (
                                  data[0x38], data[0x39], data[0x3a], data[0x3b])),
                'mac': Mac('%i:%i:%i:%i:%i:%i' % (data[0x02], data[0x03],
                                                  data[0x04], data[0x05],
                                                  data[0x06], data[0x07])),
                'gateway_ip': IpAddress('%i.%i.%i.%i' % (data[0x0c], data[0x0d],
                                                         data[0x0e], data[0x0f])),
                'fabric_port': ((data[0x22] << 8) + (data[0x23])),
                'fabric_en': bool(data[0x21] & 1),
                'xaui_lane_sync': [bool(data[0x27] & 4), bool(data[0x27] & 8),
                                   bool(data[0x27] & 16), bool(data[0x27] & 32)],
                'xaui_status': [data[0x24], data[0x25], data[0x26], data[0x27]],
                'xaui_chan_bond': bool(data[0x27] & 64),
                'xaui_phy': {'rx_eq_mix': data[0x28], 'rx_eq_pol': data[0x29],
                             'tx_preemph': data[0x2a], 'tx_swing': data[0x2b]},
                'multicast': {'base_ip': IpAddress('%i.%i.%i.%i' % (
                    data[0x30], data[0x31], data[0x32], data[0x33])),
                              'ip_mask': IpAddress('%i.%i.%i.%i' % (
                                  data[0x34], data[0x35], data[0x36], data[0x37])),
                              'rx_ips': []}
            }
``` 

Becomes this:

```python
        returnval = {
            'ip_prefix': IP_PREFIX,
            'ip': IpAddress(IP_ADDR),
            'subnet_mask': IpAddress(self._memmap_read('NETMASK')),
            'mac': Mac(self._memmap_read('MAC_ADDR')),
            'gateway_ip': IpAddress(self._memmap_read('GW_ADDR')),
            'fabric_port': self._memmap_read('PORT'),
            'fabric_en': self._memmap_read('ENABLE'),
            'multicast': {'base_ip': IpAddress(self._memmap_read('MC_IP')),
                          'ip_mask': IpAddress(self._memmap_read('MC_MASK')),
                          'rx_ips': []}
        }
```

I haven't completely gotten rid of hard-coded memory values (yet) -- partly because I'm not actually sure what some of the code does.

I think code like this needs some kind of hardware-in-the-loop testbench. I've tested this with SNAP for my needs with the old and new mappings, but can't be sure if I've accidentally broken ROACH/ROACH2/SKARAB...

Cheers,
Danny

### CODE REVIEW

**Comment by AdamI75** [comment]
> My [previous pull request](https://github.com/casper-astro/casperfpga/pull/21) added a `setup()` and `configure_core()` function for manual configuration of the 10 GbE core.
> 
> I have since learned that the location of registers changed to make it mem-map-compliant (@jack-h thinks in August 2019). This PR should work with both (although I think someone should test it on their designs and confirm I haven't broken anything).
> 
> The first thing to note is that I've added text files for both the new 'unified' memory map and the 'legacy' verson. These list register names, offsets, and sizes:
> 
> ```
> ID              OFFSET      SIZE        READ/WRITE
> ...
> MAC_ADDR        0xc         0x8         rw
> IP_ADDR         0x14        0x4         rw
> GW_ADDR         0x18        0x4         rw
> ...
> ```
> 
> This is more compact and readable (IMO) then having them defined at the top of `tengbe.py` -- particularly as most of these aren't used at all in the code. Then I've added a function to read these files, to compile a dictionary of mappings:
> 
> ```python
> memmap = {'MAC_ADDR': {'offset': 0xc, 'size': 0x8, 'rwflag': 'rw'},
>           'IP_ADDR': {'offset' 0x14, 'size': 0x4, 'rwflag': 'rw'}}
> ```
> 
> Upon instantiation, the tengbe code will check which mapping to use.
> 
> Next I added `_memmap_read()` and `_memmap_write()` functions, which are used whenever a register needs to be read or written. These functions work with 1, 2, 4 and 8 Byte registers (which requires a bit of book-keeping as only 32-bit words can actually be read or written).
> 
> This simplifies a lot of code, making it more readable. For example, the new `configure_core()` function is:
> 
> ```python
>     def configure_core(self):
>         """
>         Setup the interface by writing to the fabric directly, bypassing tap.
>         :param self:
>         :return:
>         """
>         gateway = 1 if self.gateway is None else self.gateway.ip_int
> 
>         self._memmap_write('MAC_ADDR', self.mac.mac_int)
>         self._memmap_write('IP_ADDR',  self.ip_address.ip_int)
>         self._memmap_write('NETMASK',  self.subnet_mask.ip_int)
>         self._memmap_write('GW_ADDR',  gateway)
>         self._memmap_write('PORT',     self.port)
> 
>         self.fabric_enable()
>         self.fabric_soft_reset_toggle()
> ```
> 
> Which I think is a lot clearer than `struct.pack('>LLBHHLB', huge, list, of, vars, and, zeros, here)`.
> 
> And this code
> 
> ```python
>         if self.memmap_compliant:
>             data = self.parent.read(self.name, 16384)
>             data = list(struct.unpack('>16384B', data))
>             returnval = {
>                 'ip_prefix': '%i.%i.%i.' % (data[0x14], data[0x15], data[0x16]),
>                 'ip': IpAddress('%i.%i.%i.%i' % (data[0x14], data[0x15], 
>                                                  data[0x16], data[0x17])),
>                 'subnet_mask': IpAddress('%i.%i.%i.%i' % (
>                                   data[0x1c], data[0x1d], data[0x1e], data[0x1f])),
>                 'mac': Mac('%i:%i:%i:%i:%i:%i' % (data[0x0e], data[0x0f],
>                                                   data[0x10], data[0x11],
>                                                   data[0x12], data[0x13])),
>                 'gateway_ip': IpAddress('%i.%i.%i.%i' % (data[0x18], data[0x19],
>                                                          data[0x1a], data[0x1b])),
>                 'fabric_port': ((data[0x32] << 8) + (data[0x33])),
>                 'fabric_en': bool(data[0x2f] & 1),
>                 'multicast': {'base_ip': IpAddress('%i.%i.%i.%i' % (
>                     data[0x20], data[0x21], data[0x22], data[0x23])),
>                               'ip_mask': IpAddress('%i.%i.%i.%i' % (
>                                   data[0x24], data[0x25], data[0x26], data[0x27])),
>                               'rx_ips': []}
>             }
>         else:
>             data = self.parent.read(self.name, 16384)
>             data = list(struct.unpack('>16384B', data))
>             returnval = {
>                 'ip_prefix': '%i.%i.%i.' % (data[0x10], data[0x11], data[0x12]),
>                 'ip': IpAddress('%i.%i.%i.%i' % (data[0x10], data[0x11], 
>                                                  data[0x12], data[0x13])),
>                 'subnet_mask': IpAddress('%i.%i.%i.%i' % (
>                                   data[0x38], data[0x39], data[0x3a], data[0x3b])),
>                 'mac': Mac('%i:%i:%i:%i:%i:%i' % (data[0x02], data[0x03],
>                                                   data[0x04], data[0x05],
>                                                   data[0x06], data[0x07])),
>                 'gateway_ip': IpAddress('%i.%i.%i.%i' % (data[0x0c], data[0x0d],
>                                                          data[0x0e], data[0x0f])),
>                 'fabric_port': ((data[0x22] << 8) + (data[0x23])),
>                 'fabric_en': bool(data[0x21] & 1),
>                 'xaui_lane_sync': [bool(data[0x27] & 4), bool(data[0x27] & 8),
>                                    bool(data[0x27] & 16), bool(data[0x27] & 32)],
>                 'xaui_status': [data[0x24], data[0x25], data[0x26], data[0x27]],
>                 'xaui_chan_bond': bool(data[0x27] & 64),
>                 'xaui_phy': {'rx_eq_mix': data[0x28], 'rx_eq_pol': data[0x29],
>                              'tx_preemph': data[0x2a], 'tx_swing': data[0x2b]},
>                 'multicast': {'base_ip': IpAddress('%i.%i.%i.%i' % (
>                     data[0x30], data[0x31], data[0x32], data[0x33])),
>                               'ip_mask': IpAddress('%i.%i.%i.%i' % (
>                                   data[0x34], data[0x35], data[0x36], data[0x37])),
>                               'rx_ips': []}
>             }
> ```
> 
> Becomes this:
> 
> ```python
>         returnval = {
>             'ip_prefix': IP_PREFIX,
>             'ip': IpAddress(IP_ADDR),
>             'subnet_mask': IpAddress(self._memmap_read('NETMASK')),
>             'mac': Mac(self._memmap_read('MAC_ADDR')),
>             'gateway_ip': IpAddress(self._memmap_read('GW_ADDR')),
>             'fabric_port': self._memmap_read('PORT'),
>             'fabric_en': self._memmap_read('ENABLE'),
>             'multicast': {'base_ip': IpAddress(self._memmap_read('MC_IP')),
>                           'ip_mask': IpAddress(self._memmap_read('MC_MASK')),
>                           'rx_ips': []}
>         }
> ```
> 
> I haven't completely gotten rid of hard-coded memory values (yet) -- partly because I'm not actually sure what some of the code does.
> 
> I think code like this needs some kind of hardware-in-the-loop testbench. I've tested this with SNAP for my needs with the old and new mappings, but can't be sure if I've accidentally broken ROACH/ROACH2/SKARAB...
> 
> Cheers,
> Danny

**Comment by AdamI75** [comment]
Sorry for closing, finger trouble. I wanted to add that SKARAB does not use the 10GbE interface and so it should not be an issue for us.

**Comment by telegraphic** [comment]
@AdamI75 -- no worries! Didn't look closely at the `fortygbe.py` code, but note that the author used a very similar approach! They [build a register map](https://github.com/casper-astro/casperfpga/blob/master/src/fortygbe.py#L31) and define a `_wbone_rd` and `_wbone_wr`, analogous to the `_memmap_read` and `_memmap_write` functions I defined.

As the memory addresses are the same for both 40 and 10 GbE cores, and most of the function names are identical, with a little work we could unify the `fortygbe.py` and `tengbe.py`. I don't have access to a SKARAB with a 40 GbE setup for testing though, so perhaps this is better put on a todo list for a busy week?

**Comment by AdamI75** [comment]
@telegraphic : sure we can look at doing something like this during Busy Week. We can add this to the Busy Week agenda for casperfpga.

**Comment by telegraphic** [comment]
This PR now also instantiates `snapadc` instances when programming by parsing the fpg file. The file needs to be compiled with a new version of mlib_devel that adds a tag to the fpg file. (see https://github.com/casper-astro/mlib_devel/pull/121)

**Comment by jack-h** [comment]
a) This is great, thanks!
b) is it just me who finds it strange that `Gbe.setup()` doesn't actually set any firmware registers, and instead the user has to explicitly call setup and then `TenGbe.configure_core()` afterwards?

**Comment by telegraphic** [comment]
Not just you. Sure it made sense at the time

**Comment by jack-h** [comment]
OK. Maybe one day I'll change that. One day.

**Pull request merged**
